### ISSUE TITLE
`RPIM()` optimization

### ISSUE THREAD

**Issue by vpnagraj** [databio/epihet#8]
for a given pair of samples, `RPIM()` currently calculates the score for *both* samples relative to one another ... it would be more efficient to do this once

**Comment by nsheff** [comment]
further, this `sapply` could actually be done in parallel, if desired... could we add a `cores` option to do so (maybe just sub in `lapplyAlias` ?)

https://github.com/databio/epihet/blob/731fa3ae5ebb8f67ccff8aa2315787b0dc54912d/R/calculate.R#L180-L186

**Comment by vpnagraj** [comment]
`RPIM()` optimized via 0fed7c8 ... for sample to sample comparison the function now just computes one value and then assumes the comparison in the other direction is negative of original ... when i benchmarked, this cut down the compute time by ~ 40%

**Comment by nsheff** [comment]
:trophy:
